# Generated by Django 4.0.5 on 2022-10-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='home.tag', verbose_name='My Tags'),
        ),
    ]
