# Generated by Django 4.0.5 on 2022-10-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='home.tag'),
        ),
    ]
