# Generated by Django 4.0.5 on 2022-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_customer_user_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='mobiles', to='home.customer'),
        ),
        migrations.AddField(
            model_name='tag',
            name='profile',
            field=models.ImageField(default=None, null=True, upload_to='media/images/'),
        ),
    ]
