# Generated by Django 4.0.5 on 2022-10-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_mobile_like_tag_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='like',
            new_name='likes',
        ),
    ]
