# Generated by Django 4.0.5 on 2022-10-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_like_mobile_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='likes',
            new_name='like',
        ),
    ]
